let state = {
  // Anadez
  // Application Details
  compoDataAz: [],
  compoActiveAz: false,
  tappingPressure: '',
  tappingTemperature: '',
  tappingPressureUnitSelect: 'kg/cm² g',
  tappingTemperatureUnitSelect: 'deg C',
  analyteData: [],
  analyteActive: false,
  analyteInsertActive: false,
  analyteName: '',
  analyteLow: '',
  analyteHigh: '',
  analyteUnit: 'mol %',
  customAnalyte: false,
  thermoDynamicModelSelect: 'Peng Robinson',
  serviceOfApplication: '',
  typeOfIndustrySelect: 'Oil & Gas',
  typeOfSystemSelect: 'Process',
  duplicateCompo: '',
  deletedComponent: '',
  compoBasisSelect: 'Mole % or Mole fraction',
  dewPoint: '',
  bubblePoint: '',
  showAcidDewPoint: false,
  SO2AcidDewPoint: '',
  SO3AcidDewPoint: '',
  HClAcidDewPoint: '',
  NO2AcidDewPoint: '',
  typeOfIndustry: [
    'Cement',
    'Oil & Gas',
    'Fertilizer',
    'Metals & Minerals',
    'Pulp & Paper',
    'Food & Beverage',
    'Energy & Power',
    'Textile',
    'Other',
  ],
  typeOfSystem: ['Process', 'CEM'],
  compoBasis: ['Mole % or Mole fraction', 'Mass % or Mass fraction'],
  thermoDynamicModels: ['SRK', 'Peng Robinson', 'Wilson Correlation'],
  analyteUnits: ['mol %', 'vol %', 'wt %', 'ppm v', 'ppm mol', 'ppm w'],
  // Area Class and Cert
  tempControlledEnvironment: false,
  typeOfAreaClassSelect: 'American',
  areaClassSelect: 'Class I, Div 2',
  hazGroupSelect: ['Group A', 'Group B'],
  eleCertSelect: ['CSA', 'UL', 'FM'],
  typeOfAreaClassItems: ['American', 'European'],
  areaClassAmericanItems: ['Safe Area', 'Class I, Div 1', 'Class I, Div 2'],
  areaClassEuropeanItems: ['Safe Area', 'Zone-1', 'Zone-2'],
  hazGroupAmericanItems: ['Group A', 'Group B', 'Group C', 'Group D', 'NA'],
  hazGroupEuropeanItems: ['IIC', 'IIB+H2', 'IIB', 'IIA', 'NA'],
  eleCertItems: [
    'CSA',
    'UL',
    'ATEX',
    'FM',
    'PESO',
    'JIS (Japan)',
    'GOST (Russia)',
  ],
  // Ambient and Analyzer
  minAmbientTemp: '',
  avgAmbientTemp: '',
  maxAmbientTemp: '',
  relativeHumidity: '',
  relHumidityTypeSelect: 'Non-Condensing',
  analyzerMake: '',
  analyzerModel: '',
  minAmbientAnalyzerTemp: '',
  maxAmbientAnalyzerTemp: '',
  ambientTempUnitSelect: 'deg C',
  analyzerAmbientTempUnitSelect: 'deg C',
  analyzerFlowRate: '',
  analyzerFlowRateUnitSelect: 'liter/min',
  relHumidityTypeItems: ['Non-Condensing', 'Condensing'],
  // Sample Properties
  sampleTappingPhaseSelect: 'Vapor',
  sampleTransportationPhaseSelect: 'Vapor',
  sampleMwtGiven: false,
  sampleDensityGiven: false,
  sampleMwtGivenValue: '',
  sampleDensityGivenValue: '',
  sampleDensityGivenUnitSelect: 'kg/m³',
  sampleViscosityGiven: false,
  sampleViscosityGivenValue: '',
  sampleViscosityGivenUnitSelect: 'cP',
  processLineVelocity: '',
  processLineVelocityUnitSelect: 'm/s',
  sampleTappingPhaseItems: ['Liquid', 'Vapor'],
  sampleTransportationPhaseItems: ['Liquid', 'Vapor'],
  yesNoItems: ['Yes', 'No'],
  // Probe Details
  probeMaterialSelect: 'SS-316',
  customProbeMaterial: false,
  corrosiveSample: false,
  nozzleLengthUnitSelect: 'mm',
  nozzleLength: '',
  isolationValveLength: '',
  isolationValveLengthUnitSelect: 'mm',
  processLineSizeType: 'Process Line size, Inner Diameter',
  processLineSize: '',
  processLineSizeUnitSelect: 'mm',
  processLineThickness: '',
  processLineThicknessUnitSelect: 'mm',
  extentOfProbeInsertionSelect: 'One Third Insertion,(1/3)',
  probeChannelTypeSelect: 'Pipe',
  probePipeScheduleSelect: 'SCH 40s/40/STD',
  probePipeSizeSelect: '1"',
  probeTubeSizeSelect: '¼"',
  probePipeOuterDia: '',
  probePipeThickness: '',
  probeTubeOuterDia: '',
  probeTubeThickness: '',
  probeTubeThicknessUnitSelect: 'mm',
  probePipeThicknessUnitSelect: 'mm',
  probePipeOuterDiaUnitSelect: 'mm',
  probeTubeOuterDiaUnitSelect: 'mm',
  probeFlangeSize: '1½"',
  probeFlangePressureClass: '300 #',
  probeFlangeType: 'RF',
  probeMaterialItems: [
    'SS-316',
    'Inconel',
    'Hastelloy C276',
    'SS-310',
    'Hastelloy X',
    'Ceramic',
  ],
  probeMaterialMatrix: [
    { maxTemp: 621, moc: 'SS-316' },
    { maxTemp: 870, moc: 'Inconel' },
    { maxTemp: 1010, moc: 'Hastelloy C276' },
    { maxTemp: 1093, moc: 'SS-310' },
    { maxTemp: 1176, moc: 'Hastelloy X' },
    { maxTemp: 1371, moc: 'Ceramic' },
  ],
  processLineSizeItems: [
    'Process Line size, Inner Diameter',
    'Process Line size, Outer Diameter',
  ],
  extentOfProbeInsertionItems: [
    'One Half Insertion,(1/2)',
    'One Third Insertion,(1/3)',
  ],
  probeChannelTypeItems: ['Pipe', 'Tube'],
  FlangeSizeItems: [
    '½"',
    '¾"',
    '1"',
    '1¼"',
    '1½"',
    '2"',
    '2½"',
    '3"',
    '3½"',
    '4"',
    '4½"',
    '5"',
    '6"',
    '7"',
    '8"',
    '9"',
    '10"',
    '12"',
    '14"',
    '16"',
    '18"',
    '20"',
    '22"',
    '24"',
  ],
  FlangePressureClassItems: [
    '150 #',
    '300 #',
    '400 #',
    '600 #',
    '900 #',
    '1500 #',
    '2500 #',
  ],
  probeFlangeTypeItems: ['RF', 'RTJ', 'FF'],
  // Distance and Flow
  totalDistanceTappingToCabinetShelter: '',
  totalDistanceTappingToCabinetShelterUnitSelect: 'm',
  bypassFlowMain: '',
  bypassFlowMainUnitSelect: 'liter/min',
  isSampleReturned: false,
  sampleReturnPressure: '',
  sampleReturnPressureUnitSelect: 'kg/cm² g',
  sampleReturnLineDistance: '',
  sampleReturnLineDistanceUnitSelect: 'm',
  sampleReturnLineSizeSelect: '1"',
  sampleReturnLineScheduleSelect: 'SCH 40s/40/STD',
  sampleReturnLineFlangeSize: '2"',
  sampleReturnLineFlangePressureClass: '300 #',
  sampleReturnTubeThickness: '',
  sampleReturnTubeOuterDia: '',
  sampleReturnTubeSizeSelect: '½"',
  sampleReturnTubeOuterDiaUnitSelect: 'mm',
  sampleReturnTubeThicknessUnitSelect: 'mm',
  roughnessParameter: 0.03,
  // Transportation
  primaryTransportTubeThickness: '',
  primaryTransportTubeOuterDia: '',
  secondaryTransportTubeThickness: '',
  secondaryTransportTubeOuterDia: '',
  tertiaryTransportTubeThickness: '',
  tertiaryTransportTubeOuterDia: '',
  isPSHS: false,
  isPrimaryPR: false,
  isSecondaryPR: false,
  primaryTransportDistance: '',
  primaryTransportDistanceUnitSelect: 'm',
  primaryPRSetPressure: '',
  primaryPRSetPressureUnitSelect: 'kg/cm² g',
  primaryTransportTubeSizeSelect: '¼"',
  primaryTransportTubeOuterDiaUnitSelect: 'mm',
  primaryTransportTubeThicknessUnitSelect: 'mm',
  secondaryTransportDistance: '',
  secondaryTransportDistanceUnitSelect: 'm',
  secondaryPRSetPressure: '',
  secondaryPRSetPressureUnitSelect: 'kg/cm² g',
  secondaryTransportTubeSizeSelect: '¼"',
  secondaryTransportTubeOuterDiaUnitSelect: 'mm',
  secondaryTransportTubeThicknessUnitSelect: 'mm',
  tertiaryTransportDistance: '',
  tertiaryTransportDistanceUnitSelect: 'm',
  tertiaryTransportTubeSizeSelect: '¼"',
  tertiaryTransportTubeOuterDiaUnitSelect: 'mm',
  tertiaryTransportTubeThicknessUnitSelect: 'mm',
};

// console.log(state);
